name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t vnphu18/deploy_webweather .
    - name: Push to Dockerhub
      run: docker push vnphu18/deploy_webweather:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Đảm bảo phần deploy chỉ chạy khi phần build thành công

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Lấy mã nguồn từ GitHub

    - name: Set up AWS CLI
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

    - name: Deploy Docker image to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # Secret chứa private key của EC2
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}  # Public IP của EC2 instance
      run: |
        # Tạo file private key để sử dụng kết nối SSH vào EC2
        echo "$PRIVATE_KEY" > vp-keypair.pem
        chmod 600 vp-keypair.pem
        
        # SSH vào EC2 và deploy Docker image
        ssh -o StrictHostKeyChecking=no -i vp-keypair.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          # Pull Docker image từ Docker Hub
          docker pull vnphu18/deploy_webweather:latest

          # Dừng và xoá container cũ (nếu có)
          docker stop weather-app || true
          docker rm weather-app || true

          # Chạy container mới với image mới
          docker run -d --name weather-app -p 80:80 vnphu18/deploy_webweather:latest
        EOF    
